#!/usr/bin/env python3
"""Generate the mini opening book "Buch 2d" (Android only).

Exact scores of all seven moves for every position with 0, 1 or 2 stones
(1 + 7 + 49 = 57 positions), computed with the original engine (bitbully
0.0.79, C++ core, full search with the 12-ply-dist book). Output:
core/src/main/kotlin/io/github/patrickric/connectfourstudio/core/engine/MiniBookData.kt

Usage:
  PYTHONDONTWRITEBYTECODE=1 "<Qt dir>/.venv/bin/python" scripts/gen_minibook.py
"""

import os

import bitbully as bb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "core", "src", "main", "kotlin", "io", "github", "patrickric",
                   "connectfourstudio", "core", "engine", "MiniBookData.kt")


def main():
    agent = bb.BitBully("12-ply-dist")
    seqs = [[]] + [[a] for a in range(7)] + [[a, b] for a in range(7) for b in range(7)]
    rows = []
    for seq in seqs:
        board = bb.Board.from_moves(seq)
        scores = agent.score_all_moves(board, max_depth=-1)
        rows.append([scores[c] for c in range(7)])
        print(seq, rows[-1])
    lines = [
        "// Generated by scripts/gen_minibook.py with bitbully 0.0.79 (full search) - do not edit.",
        "package io.github.patrickric.connectfourstudio.core.engine",
        "",
        "/**",
        " * Scores of the seven columns for the 57 positions with 0-2 stones, in the",
        " * order: empty board; after column 0..6; after columns (a, b), a = 0..6, b = 0..6.",
        " */",
        "internal object MiniBookData {",
        "    val SCORES: IntArray = intArrayOf(",
    ]
    for seq, row in zip(seqs, rows):
        moves = "".join(str(m + 1) for m in seq) or "-"
        lines.append("        " + ", ".join(str(v) for v in row) + f", // {moves}")
    lines += ["    )", "}", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
